### ISSUE TITLE
Putting keyboard under the phone without overlap

### ISSUE THREAD

**Issue by dumblob** [Dakkaron/Fairberry#6] opened 2022-05-03 18:03 UTC
I wonder whether you experimented with putting the keyboard under the phone (like BlackBerry KEY 1, BlackBerry KEY 2, Unihertz Titan Slim)?

If not, would you have any suggestions, observations, or links?

Thanks!

**Comment by Dakkaron** [comment] 2022-05-03 20:35
I actually tried that before settling on this design, where the keyboard overlaps the chin of the phone.
The problem is, that that causes further imbalance and makes the phone even longer.

It might work with a smaller phone but the FP4 is tall as it is. Maybe, the FP4 isn't the best phone for this purpose, but it's the one I have.

I first had the solution on my temporary Honor 9 Lite, and there the balance and size was better.

I was thinking about remaking the case in OpenSCAD so that anyone can generate a version fitting for their own phone. Shouldn't be too hard.

Another problem, though, would be that the USB connector probably would be in the way of the keyboard. So it would probably have to be thicker anyways.

**Comment by dumblob** [comment] 2022-05-03 21:52
>The problem is, that that causes further imbalance and makes the phone even longer.

Regarding imbalance it's from my experience more about getting used to rather than a serious issue (on my BlackBerry I've learned to use side bezels by my thumbs as stabilizer - it could be even improved if the case is designed with a few millimeters more thickness at the "balance point" on both sides).

But the length, that's already a problem, no doubts.

>I was thinking about remaking the case in OpenSCAD so that anyone can generate a version fitting for their own phone. Shouldn't be too hard.

Maybe adding a "Sheet" in FreeCAD with some variables (dimensions, radiuses of long top edges, short top edges, long bottom edges, short bottom edges) could be enough (and simpler for beginners)?

>Another problem, though, would be that the USB connector probably would be in the way of the keyboard. So it would probably have to be thicker anyways.

1-2 mm is fine. 3 or more mm looks gross though :wink:.

Or maybe a simple custom tiny narrow PCB with the USB connector soldered on it could be an alternative to explore. IDK

**Comment by Dakkaron** [comment] 2022-05-04 06:03
> Regarding imbalance it's from my experience more about getting used to rather than a serious issue (on my BlackBerry I've learned to use side bezels by my thumbs as stabilizer - it could be even improved if the case is designed with a few millimeters more thickness at the "balance point" on both sides).

Currently, I hook my middle fingers into the back of the keyboard. This helps with the balance as well.

> But the length, that's already a problem, no doubts.

Another problem with the length is durability. The keyboard is a weak point in the structure. If it's too long and you pocket the phone with the keyboard attached, it becomes easier to accidentally break, if it's longer.

> Maybe adding a "Sheet" in FreeCAD with some variables (dimensions, radiuses of long top edges, short top edges, long bottom edges, short bottom edges) could be enough (and simpler for beginners)?

Thingiverse has this Customizer feature, where you import OpenSCAD code and it generates a nice GUI form where the users can input their values and it generates a fitting part in STL format.

> 1-2 mm is fine. 3 or more mm looks gross though 😉.

I understand what you mean^^

Currently, the thickness is mostly limited by the keyboard's hooks at the front. I guess, I could remove the hooks to shave off some thickness. But then the limiting factor becomes the PCB and the parts on it. If I find someone to make a custom PCB (or somehow manage to learn KiCAD^^), it might be possible to shave off some more thickness. Another problem is the keyboard's flex PCB connector. It needs to be bent twice to fit under the keyboard, and I don't want the bend radius to be too small, cause that might break the flex PCB.

I'd actually really like to use the Keyone-Keyboard, because that would solve some issues (it's a bit shorter and the connector is at a much better position), but there is no information at all about it, I don't even know the name of the connector...

**Comment by dumblob** [comment] 2022-05-04 07:56
> Another problem with the length is durability. The keyboard is a weak point in the structure. If it's too long and you pocket the phone with the keyboard attached, it becomes easier to accidentally break, if it's longer.

Actually durability can be solved quite easily as far as my experience goes - materials, thickness, making the keyboard into a full-covering cover, etc.

> > Maybe adding a "Sheet" in FreeCAD with some variables (dimensions, radiuses of long top edges, short top edges, long bottom edges, short bottom edges) could be enough (and simpler for beginners)?
> 
> Thingiverse has this Customizer feature, where you import OpenSCAD code and it generates a nice GUI form where the users can input their values and it generates a fitting part in STL format.

Oh, didn't know about this feature. Is it available also for non-registered users?

If not, then there is not that much of a difference between the work needed in both approaches :wink: (it'll be anyway dominated by looking for a caliper and measuring all the dimensions etc.).

> Currently, the thickness is mostly limited by the keyboard's hooks at the front. I guess, I could remove the hooks to shave off some thickness.

I didn't even notice you didn't remove them :smile: (when I was looking at aliexpress photos of the keyboard the first thought was to remove them and other surrounding "overhangs" etc. at all cost :wink:).

>But then the limiting factor becomes the PCB and the parts on it. If I find someone to make a custom PCB (or somehow manage to learn KiCAD^^), it might be possible to shave off some more thickness. 

Definitely. The PCB can be actually very small. I know one PCB ninja - but he will have time for it first in couple of months probably. I'll ask him. But in no way I want to discourage you - learning KiCAD basics is super useful!

>Another problem is the keyboard's flex PCB connector. It needs to be bent twice to fit under the keyboard, and I don't want the bend radius to be too small, cause that might break the flex PCB.

This one should be really easy to solve - just leave groovy holes in the custom PCB (and/or other plates/material layers) at the places where the folds shall happen and they'll form a nice round bend with >1 mm radius. Or at least that's how I did it in the past.

> I'd actually really like to use the Keyone-Keyboard, because that would solve some issues (it's a bit shorter and the connector is at a much better position), but there is no information at all about it, I don't even know the name of the connector...

Yep. OTOH maybe the [fully automated sniffer](https://www.instructables.com/How-to-Make-a-USB-Laptop-Keyboard-Controller/ ) could do the work for us?

**Comment by Dakkaron** [comment] 2022-05-04 10:30
>Actually durability can be solved quite easily as far as my experience goes - materials, thickness, making the keyboard into a full-covering cover, etc.

Sure, but on the one hand, using metal will make the thing pretty heavy. On the other hand, anything except 3D printed parts is hard to get and/or expensive.

>I didn't even notice you didn't remove them 😄 (when I was looking at aliexpress photos of the keyboard the first thought was to remove them and other surrounding "overhangs" etc. at all cost 😉).

The keyboard itself is 3mm thick. The hooks are another 3mm. I didn't remove the hooks, because I fit the PCB in there anyway. The PCB + adhesive + components and leads are almost 3mm in height, so the hooks don't add much.

The whole assembly currently adds 8mm on top of the phone, and 1mm at the bottom. Since the PCB assembly is now a little flatter than it used to be, I could probably shave off 1-2mm at the top.

Looking at my fat Fairphone 4, it has about 3mm above the USB C port. So with a bit of tinkering, it could be possible to fit the keyboard over the USB C connector and be almost flush with the phone's  screen.

> Definitely. The PCB can be actually very small. I know one PCB ninja - but he will have time for it first in couple of months probably. I'll ask him. But in no way I want to discourage you - learning KiCAD basics is super useful!

That would be a lot of help! I've been trying to learn KiCAD for a while now. I can do footprints and schematics, but I got lost at actually creating the PCB.

I've asked a few guys on fiverr, but didn't get any replies yet.

> Yep. OTOH maybe the [fully automated sniffer](https://www.instructables.com/How-to-Make-a-USB-Laptop-Keyboard-Controller/) could do the work for us?

That thing is cool! Actually, I don't think it would be very hard to decode the keyboard matrix. The biggest hurdle is figuring out what physical connector is used and making an adapter PCB to interface with an Arduino or something.


> Oh, didn't know about this feature. Is it available also for non-registered users?
If not, then there is not that much of a difference between the work needed in both approaches 😉 (it'll be anyway dominated by looking for a caliper and measuring all the dimensions etc.).

I don't know, actually.

Yeah, I've first used the dimensions for my phone that I found on the internet, but they don't apply once you have a screen protector on.

**Comment by dumblob** [comment] 2022-05-04 13:26
> Sure, but on the one hand, using metal will make the thing pretty heavy. On the other hand, anything except 3D printed parts is hard to get and/or expensive.

No need for metal nor any similar "heavy duty" thing. There are plenty of 3D printing solutions - making the sides of the cover 3.5 mm thick (100% infill) is so strong even with PLA that you'd have a good chance breaking your phone first before breaking the cover. And there are even better options - PET is much stronger than PLA. But that's still nothing compared to [Nylon in Multi Jet Fusion](https://jlcpcb.com/3d-printing ) (definitely see some youtube videos about 3D printed Nylon).

> Looking at my fat Fairphone 4, it has about 3mm above the USB C port. So with a bit of tinkering, it could be possible to fit the keyboard over the USB C connector and be almost flush with the phone's screen.

Exactly this was the idea (with some negligible nuances among other phones on the market). Fairphone 4 is not that long, so this is an ideal example of keyboard under the phone without overlap :smile:.

> That would be a lot of help! I've been trying to learn KiCAD for a while now. I can do footprints and schematics, but I got lost at actually creating the PCB.

Very well! Footprints are usually the most boring and time consuming task in such small non-HF projects. Any such partial work would help us (and the PCB ninja :wink:) to get to prototyping quicker. Do you have the partial work somewhere?

Another thing I know from PCB ninja is to know the exact dimensions and shape of the needed PCB to avoid several iterations just due to non-matching size/shape.

Do you think you could try positioning the keyboard under the phone with zero overlap and then trying to figure out the shape of the PCB needed to have the USB connector soldered directly on the PCB (from the side or on top as SMD)? The shape (with proper dimensions) can then be easily imported as SVG into KiCAD IIRC.

>The biggest hurdle is figuring out what physical connector is used and making an adapter PCB to interface with an Arduino or something.

My idea above about the custom PCB was to have both the Teensy/Arduino MCE and the keyboard physical connector as well as the USB connector on a single custom PCB.

In an ideal world we could even try to make the PCB shape more generic and only exchange the USB connector (micro USB vs. micro USB flipped vs. USB-C) and the 3D printed case. The PCB itself would stay untouched making it easy to port the keyboard to different phones.

But this is only if we get bored :wink:.

**Comment by dumblob** [comment] 2022-05-04 14:52
>I was a bit hesitant, though, to solder the USB connector directly to the PCB, because that would be a very easy point of failure.

The plastic cover shall make it sturdy enough IMHO. What do you think?

>In that case, I'd make the PCB in a way, that the USB connection is routed to a location where the connector can be soldered directly to the board and also to through-holes for wired assembly.

:+1:

If you already have something unfinished, feel free to publish it and I'll forward it to the PCB ninja and see what he'll tell me.

Btw. are you satisfied with the power consumption? I've had some discussion about power consumption and [latency](https://www.youtube.com/watch?v=vOvQCPLkPt4 ) in https://github.com/PMunch/badger/issues/4 and kind of started liking the simplicity and utility of the Badger keyboard firmware. Feel free to take a look.

>Tbh, I'd only do USB-C. Micro-USB is very much on it's way out. Also, from what I understand, Micro-USB-B-OTG needs slightly different wireing from USB-C-Client.

Oh, I didn't think of the different wiring. Maybe make blind traces with pads at their ends for potential later "0 resistance SMD resistors" soldering for those who would want to solder a micro USB connector instead (yep, I still own and use some such devices :wink:) and thus needed to cut some traces and solder some other traces together using the pads and 0 resistors?

**Comment by dumblob** [comment] 2022-05-04 20:50
> The problem is this: If the connector is soldered directly to the board, then it's plugged into the phone by sliding the keyboard on. That means, if, for some reason, the plug isn't lined up perfectly, and misses the port, all that force goes directly to the solder joints. If you are unlucky, this might rip off the solder pads. That is almost impossible to repair.
> 
> I've had something like this on a laptop, where the USB port was ripped the PCB.
> 
> That's what I am trying to avoid. If the plug is wired, the worst that can happen is that you have to resolder the wires.

That is true and I had similar issues on older laptops. OTOH we might have the luxury to make part of the PCB (if dimensions allow for it) partially flexible by creating something akin a [zig zag pattern](https://ploopy.co/shop/thumb-trackball-full-kit/ ). Note different flexible patterns can be easily made also in the orthogonal/lateral direction. Of course mounting holes and any "supports" in the plastic cover shall reflect this.

> I haven't noticed any power consumption impact on my phone at all. The maximum that it can draw is <40mAh. That would drain my phone's battery in 100h. That means, the difference that the keyboard makes, is so small, that it gets completely lost in the regular daily power usage fluctuations.

Perfect!

>Latency is pretty good, as far as I can see. At no point did I feel that the latency was low. That said, I didn't try hardcore-gaming on the keyboard.

Instead of hardcore-gaming you could simply make a recording like Dan Luu in https://danluu.com/keyboard-latency/ . And one more link to consider :wink: https://bdickason.com/posts/speed-is-the-killer-feature/ .

> Today I implemented some power saving features, which disable the backlight and put the microcontroller to sleep when the keyboard hasn't been used for a minute. Disabling the backlight is a definitive must and works fine. Putting the microcontroller to sleep doesn't work nearly as nicely as I hoped, since it also disables the USB and then requires 1-2sec to reconnect. I think, I'll put that behind a default-disabled `#define`.

Yep, I myself wouldn't use any such feature which introduces any such delay.

> Another useful power saving option would be to remove the Arduino's LEDs. They are probably the thing that consumes the most power.

Right. Second biggest source of consumption is unnecessarily high frequency of the MCU. And the third biggest source of consumption is unnecessary scanning of the matrix, but that's probably already good enough or even optimized (usually problems appear with multiplexers/port_extenders but there seem to be none here as far as I skimmed this repo).

> I see what you mean. One problem that I see is that we'd have to fit the connection points for two different plugs at the same position (or even three, if we support a flipped Micro USB connector). It's really hard to find two different Micro USB plugs, where all the leads and the feet are at the exact same position. I fear, it's going to be nearly impossible to find a Micro USB plug and an USB-C plug with the same footprint.
> 
> In this case, we might be better off making two separate versions.

You're right.

Thanks for bringing up these realistic observations to tame my wild ideas!

**Comment by Dakkaron** [comment] 2022-05-05 15:11
I did a bit of thinking. If we allow the keyboard to raise up to 2mm above the phone, we can easily fit even a wired USB C port under the keyboard. Actually, it might work as is on my phone. I'll try to print something if I find the time.

I'd like to have the plug to be connected using wires and then attach the plug PCB to the case, so that it's plugged in by attaching the case, but without putting strain onto solder leads.

> That is true and I had similar issues on older laptops. OTOH we might have the luxury to make part of the PCB (if dimensions allow for it) partially flexible by creating something akin a [zig zag pattern](https://ploopy.co/shop/thumb-trackball-full-kit/). Note different flexible patterns can be easily made also in the orthogonal/lateral direction. Of course mounting holes and any "supports" in the plastic cover shall reflect this.

Is this durable? Flexing a non-flex PCB doesn't sound safe. But I don't have any experience with that.

Btw, I measured the discharge rate on my phone, and it discharged by around 60mAh, which is probably due to DCDC power conversion that I didn't account for. Also, I guess, the USB stack on the phone also consumes some power. The resolution of my phone's discharge measurement is 10mAh, so the 60mAh is a quite rough guess.

If the keyboard is in sleep mode, it consumes less than the phone can measure.

> Instead of hardcore-gaming you could simply make a recording like Dan Luu in https://danluu.com/keyboard-latency/ . And one more link to consider 😉 https://bdickason.com/posts/speed-is-the-killer-feature/ .

I don't have a logic analyser, so that's hard for me to measure. But the latency is not so slow that I would notice at all.

> Yep, I myself wouldn't use any such feature which introduces any such delay.

Maybe I could add some key combination or a switch that puts the keyboard to sleep mode or something.

> Right. Second biggest source of consumption is unnecessarily high frequency of the MCU. And the third biggest source of consumption is unnecessary scanning of the matrix, but that's probably already good enough or even optimized (usually problems appear with multiplexers/port_extenders but there seem to be none here as far as I skimmed this repo).

Reducing the clock frequency from 16MHz to 1MHz will reduce the power consumption by ~15mAh. That would be quite a bit.
I don't use multiplexers or something, only direct GPIO.

**Comment by dumblob** [comment] 2022-05-05 22:11
> I did a bit of thinking. If we allow the keyboard to raise up to 2mm above the phone, we can easily fit even a wired USB C port under the keyboard. Actually, it might work as is on my phone. I'll try to print something if I find the time.

Any pictures of printed stuff or just 3D models would be appreciated to see how it would look like in practice :wink:.

> I'd like to have the plug to be connected using wires and then attach the plug PCB to the case, so that it's plugged in by attaching the case, but without putting strain onto solder leads. That way, it would also be much easier to allow for Micro USB ports as well.

That's also an option - but much more work and hassle IMHO. But maybe it's not that bad. IDK

> Is this durable? Flexing a non-flex PCB doesn't sound safe. But I don't have any experience with that.

Yes, it is really durable. It's being used in professional products of known brands (incl. e.g. Siemens AG). So I wouldn't be afraid of it.

> Btw, I measured the discharge rate on my phone, and it discharged by around 60mAh, which is probably due to DCDC power conversion that I didn't account for. Also, I guess, the USB stack on the phone also consumes some power. The resolution of my phone's discharge measurement is 10mAh, so the 60mAh is a quite rough guess.

Yes, power conversion is another source of huge leakage. Thanks for noticing!

> > Instead of hardcore-gaming you could simply make a recording like Dan Luu in https://danluu.com/keyboard-latency/ . And one more link to consider wink https://bdickason.com/posts/speed-is-the-killer-feature/ .
> 
> I don't have a logic analyser, so that's hard for me to measure. But the latency is not so slow that I would notice at all.

I mean, Dan didn't use any logic analyzer but measured end-to-end latency with a camera (60fps is a pretty standard nowadays; with sport cameras you get (much) more).

> Maybe I could add some key combination or a switch that puts the keyboard to sleep mode or something.

I for myself wouldn't use such feature either - it's no different than pressing a button and waiting 2s for it to react. It's also a similar mental model to unplugging the whole keyboard from the phone. So really of no use for my workflow. But maybe for yours it'd be a different story.

> Reducing the clock frequency from 16MHz to 1MHz will reduce the power consumption by ~15mAh. That would be quite a bit.

:+1:

>I don't use multiplexers or something, only direct GPIO.

:+1:

**Comment by Dakkaron** [comment] 2022-05-06 22:16
Since it's more of a discussion than a straight issue, I'd suggest, we continue our discussion in the discussions section.

Here is the discussion regarding the flat keyboard: https://github.com/Dakkaron/Fairberry/discussions/8

Here is one regarding the power consumption: https://github.com/Dakkaron/Fairberry/discussions/9

And this one is regarding the connector: https://github.com/Dakkaron/Fairberry/discussions/10

Did I miss anything?

I'll close this issue, since the discussion feature is more useful for discussions^^

**Closed by Dakkaron** 2022-05-06 22:16 UTC

**Comment by dumblob** [comment] 2022-05-07 08:56
Thanks! I'll take a look at the separate threads later - now I'm too busy.
